# Generated by Django 3.0.3 on 2020-02-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_user_username'),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perms',
            new_name='Perm',
        ),
    ]
