# Generated by Django 3.0.3 on 2020-02-18 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
